### ISSUE TITLE
AttributeError: module 'g2o' has no attribute 'Flag'

### ISSUE THREAD

**Issue by zxl152723** [luigifreda/pyslam#72]
run main_slam.py

zhang@DESKTOP-NCMOEKG:/mnt/d/pyslam-master$ python main_slam.py
Traceback (most recent call last):
  File "main_slam.py", line 29, in <module>
    from slam import Slam, SlamState
  File "/mnt/d/pyslam-master/slam.py", line 35, in <module>
    from map import Map
  File "/mnt/d/pyslam-master/map.py", line 41, in <module>
    import optimizer_g2o
  File "/mnt/d/pyslam-master/optimizer_g2o.py", line 36, in <module>
    def bundle_adjustment(keyframes, points, local_window, fixed_points=False, verbose=False, rounds=10, use_robust_kernel=False, abort_flag = g2o.Flag()):
AttributeError: module 'g2o' has no attribute 'Flag'

**Comment by boyueluzhipeng** [comment]
你是怎么解决的，感谢分享下

**Comment by zahidesatmutlu** [comment]
It's works on Python 3.6.9 and Ubuntu 18.04 WSL2 Subsystem.

**Comment by hbonnavaud** [comment]
Hi @DMUZhangXianglong, how did you solved this issue?
